children/admin.py
children/models.py
children/schema.py
children/tests/snapshots/snap_test_api.py
children/tests/test_api.py
common/tests/utils.py
users/tests/test_api.py

The PR contains a couple of added validations and in addition minor fixes to permission handling and tweaks to tests.

KK-144 | Validations and fixes

---

children/admin.py
users/admin.py

Some minor improvements for the Django admin UI.

Django admin UI tweaks

---

common/models.py
events/admin.py
events/models.py
events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py
kukkuu/schema.py
venues/admin.py
venues/models.py
venues/schema.py
venues/tests/snapshots/snap_test_api.py
venues/tests/test_api.py

Create event/venue/occurrences api
Override TranslatableModel to be able to update translation easier
Some unit tests
Improve admin interface a bit by adding inline form

KK-72 | Add event mutation

---

requirements.txt

This fixes admin UI logout which was broken.

Upgrade django-helusers to v0.5.5

---

requirements.txt

The previous version had a bug in it's migrations.

Upgrade django-helusers to v0.5.6

---

README.md
common/tests/conftest.py
events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py
kukkuu/settings.py
requirements.in
requirements.txt
venues/tests/snapshots/snap_test_api.py
venues/tests/test_api.py

- Update README (important)
- Add test for upload image mutation
- Add `django-cleanup` to clean unused images when delete/update object
- Add missing image field to update event mutation
- Remove id from test query to avoid id conflict

Add test for upload image, django-cleanup, update README, fix update input

---

children/tests/test_notifications.py
common/tests/utils.py
events/__init__.py
events/admin.py
events/apps.py
events/factories.py
events/models.py
events/notifications.py
events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/snapshots/snap_test_notifications.py
events/tests/test_api.py
events/tests/test_notifications.py
events/utils.py
venues/tests/snapshots/snap_test_api.py

- Add `PublishEventMutation`
- Notifications to guardians when an event published
- Update django admin interface to support publish event action

KK-260 | Publish event mutation

---

events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py
venues/schema.py
venues/tests/snapshots/snap_test_api.py
venues/tests/test_api.py

Add normal translation fields to Venue and Event

Add language support to venue and events

---

events/filters.py
events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py
events/utils.py
kukkuu/settings.py
requirements.in
requirements.txt

Add occurrence filter
- Filter by date
- Filter by time of day

KK-298 | Add occurrence filters

---

Dockerfile
README.md
crontab
docker-compose.env.yaml.example
docker-entrypoint.sh
kukkuu/settings.py
requirements.txt

- Updated `django-ilmotin` version to push mail to queue instead of firing them immediately
- Update configuration to use queue notification
- Change image user to root to start cron service, update entrypoint to switch to `appuser` user later

KK-267 | Delayed notifications

---

events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py
venues/schema.py
venues/tests/test_api.py

- Use LanguageEnum in translations language code
- Remove some unused fields in OccurrenceNode

Use LanguageEnum in translation language code

---

children/schema.py
children/tests/snapshots/snap_test_api.py
children/tests/test_api.py
events/filters.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py

Added a filter `upcoming [True/False]` to Occurrences query

KK-321 | Update child occurrences query

---

.gitlab-ci.yml

Added staging config for mail gun
`$SECRET_MAILGUN_API_KEY` is a gitlab custom variable which has been added by #infra guy

KK-340 | Add env for email config in staging

---

requirements.in
requirements.txt

Added `django-storage[arure]`.
In production, we use Azure Blob storage instead of Google Cloud Storage
The env var and settings are already there, just need to add pip dependency.
Tested and worked in my local env

Add django-storage[azure]

---

users/schema.py

Make language required in myProfile query

---

.gitlab-ci.yml

Following guideline from: 
https://helsinkisolutionoffice.atlassian.net/wiki/spaces/DD/pages/338984961/Object+storage

Update file crendential variable in QA env

---

.gitlab-ci.yml
common/utils.py
events/admin.py
events/consts.py
events/models.py
events/notifications.py
events/schema.py
events/signals.py
events/tests/test_notifications.py
events/utils.py
kukkuu/settings.py

* Changed event publish notification to be sent to every child of the
project. Previously there was only one notification sent per guardian.
* Made event URL (in UI) available to event published notification

KK-436 | Event published notification enhancements

---

events/admin.py
events/models.py
events/schema.py
events/signals.py
events/tests/snapshots/snap_test_notifications.py
events/tests/test_notifications.py

Changed unenrolment notification to be not sent when the related Occurrence is deleted. Also some other enhancements related to enrolment notifications.

KK-521 | Enrolment notification modifications

---

children/schema.py
events/models.py
events/schema.py
venues/schema.py

* Fixed delete mutations' log messages
* Added event info to occurrence mutation log messages

Improve log messages

---

projects/admin.py
users/admin.py

To improve project user handling in admin UI when there is a big number
of users:
* Added projects inline to user detail view
* Changed users multiselect to users inline in project detail view
* Added UUID field to user list view

Improve project user handling in admin UI

---

children/schema.py
languages/management/commands/add_languages.py
languages/models.py
languages/tests/conftest.py
languages/tests/snapshots/snap_test_add_languages_command.py
languages/tests/snapshots/snap_test_api.py
languages/tests/test_add_languages_command.py
languages/tests/test_api.py

Tests and a couple of bug fixes for languages app.

KK-528 | Language tests

---

children/factories.py
messaging/admin.py
messaging/factories.py
messaging/models.py
messaging/schema.py
messaging/tests/conftest.py
messaging/tests/snapshots/snap_test_sending.py
messaging/tests/test_sending.py
subscriptions/tests/test_api.py

This PR adds functionality for sending and manual messages. API for that has been implemented already.
Manual messages' sending has quite a complex filtering rules specified [here](https://helsinkisolutionoffice.atlassian.net/browse/KK-582).

KK-582 & KK-604 | Manual messages functionality

---

common/utils.py
events/factories.py
events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py

* EventGroup(Id) (get single EventGroup)
* EventsAndEventGroups(projectId) (get all EventGroups and all Events that don't belong to any group)

KK-647 | EventGroup GQL queries

---

children/schema.py
children/tests/snapshots/snap_test_api.py
children/tests/test_api.py
common/tests/conftest.py
events/factories.py
events/filters.py
events/models.py
events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py

Details of the changes can be found in the commit messages.

KK-662 | Event group availability related API additions

---

children/admin.py
children/tests/snapshots/snap_test_notifications.py
events/admin.py
events/models.py
events/tests/snapshots/snap_test_notifications.py
projects/admin.py
subscriptions/tests/snapshots/snap_test_notifications.py
users/admin.py
users/models.py
users/tests/snapshots/snap_test_notifications.py
users/tests/test_models.py

Various smallish improvements to admin UI and a few other tweaks.

KK-690 | admin UI improvements

---

.github/workflows/review.yml
.github/workflows/staging.yml

Use KuVa Tunnistamo with dynamic URL

---

README.md
common/templates/notification_change_list.html
common/tests/conftest.py
events/notifications.py
importers/admin.py
importers/management/commands/import_notifications.py
importers/notification_importer.py
importers/templates/notification_change_list.html
importers/tests/conftest.py
importers/tests/snapshots/snap_test_notification_importer.py
importers/tests/test_notification_importer.py
importers/tests/utils.py
kukkuu/settings.py
requirements-dev.in
requirements-dev.txt
requirements.in
requirements.txt
subscriptions/notifications.py

Added an importer that imports django-ilmoitin's NotificationTemplates from a Google Sheets spreadsheet.
To use the importer, one must first configure setting `KUKKUU_NOTIFICATIONS_SHEET_ID`. After that, the importer can be run
with either
1) management command `import_notifications` that imports and updates every `NotificationTemplate`, or
2) via notification list view in Django admin UI, which provides finer control on which notifications to update
Example sheet: https://docs.google.com/spreadsheets/d/1mNp6o5-DsUGQN_uRW0YSjJg771PwlFQJFa7cRwqIWso/edit#gid=0
Q: Isn't this a bit over-engineered?
A: Yes.

KK-695 | Notification importer

---

.github/workflows/review.yml
.github/workflows/staging.yml

Resource requests and limits set

---

.github/workflows/production.yml
.github/workflows/staging.yml

These configurations have been released to production with a tag pointing to the commit on this branch as a hotfix, but they have not been merged into master yet.

New Mailgun configuration

---

.github/workflows/production.yml
.github/workflows/staging.yml
events/models.py
events/tests/test_notifications.py
events/utils.py

Fixed a language bug, and implemented a couple of improvements to event/event group publish notification sending. Details in the commit messages.

KK-752 | Notification sending improvements

---

events/schema.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py

Added
*  ticket system type to event add and update mutation inputs. Ticket system cannot be changed if the event is already published.
* ticket system URL to occurrence add and update mutation inputs

KK-766 | Ticket system related mutations

---

events/notifications.py

KK-828. The registration of the new notification template was undone.

Registered the occurrence feedback notification template

---

events/tests/test_api.py

Added a test about ticket validity check after unenrolment is done

---

messaging/schema.py
messaging/tests/snapshots/snap_test_api.py
messaging/tests/test_api.py

KK-829. The SMS messages should be able to be sent directly without any external add message step.

Added a feature for direct sending the message with addMessageMutation

---

events/tests/test_models.py

Added tests for Event's and EventGroup's can_child_enroll -methods

---

.github/workflows/staging.yml
kukkuu/settings.py

Check if credentials file is exists

cronjob-is-broken-KK-754

---

.github/workflows/load_tests.yml
.github/workflows/production.yml
.github/workflows/review.yml
.github/workflows/staging.yml
k6LoadTests.js

- Horizontal pod autoscaler [DEVOPS-392](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-392)
- Load tests on staging [DEVOPS-428](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-428)
- Prevent parallel deployment [DEVOPS-429](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-429)

Horizontal pod autoscaler

---

events/schema.py

KK-903. Alternative implementation for ticket system passwords importing. Using the create_bulk -command, the insert-process will be a single request, but the errors other than integrity issues will just raise an error that we cannot handle.
NOTE: This does not improve much and the for-loop-importing should not be an issue in Kukkuu at all. Just wanted to try this and ask for your thoughts

Use bulk_create to import ticket system passwords

---

kukkuu/settings.py

Mailer lockfile on tmp -folder
[KK-964](https://helsinkisolutionoffice.atlassian.net/browse/KK-964)

Mailer lockfile path

---

k6LoadTests.js

[DEVOPS-450](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-450)

k6 loadtest url from environmentvariable

---

azure-pipelines-release.yml
azure-pipelines-test.yml

DevOps pipelines refactor. Pipelines for test and release

build: devops pipelines test and release

---

events/models.py
events/schema.py
events/tests/test_api.py
venues/schema.py

Added some database prefetching and new count fields `attendedEventCount` and `freeSpotNotificationSubscriptionCount` to `OccurrenceNode` so that the admin UI can get the needed occurrences data faster.

KK-976 | Improve occurrence queries' performance

---

Dockerfile

Use ubi image as base
[DEVOPS-560](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-560)
[DEVOPS-560]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dockerfile base on ubi image DEVOPS-560

---

browser-tests/tests/pages/event.ts
browser-tests/tests/pages/eventGroup.ts
browser-tests/tests/pages/message.ts
browser-tests/tests/pages/occurence.ts
browser-tests/tests/pages/project.ts
browser-tests/tests/pages/user.ts
browser-tests/tests/pages/venue.ts

KK-1017. There were multiple save buttons where the regex matched.

test: fix the browser tests save-button clicking

---

users/schema.py
users/tests/mutations.py
users/tests/snapshots/snap_test_api.py
users/tests/snapshots/snap_test_notifications.py
users/tests/test_api.py
users/tests/test_notifications.py
users/utils.py

feat: send the email change verification token to the new email

---

verification_tokens/admin.py

KK-1072.
- Add a date hierarchy.
- Fix the search and add some new parameters.
- Add a filter.
- Use an autocomplete field for user selection.

refactor: improve verification tokens admin page

---

README.md
docs/setup-keycloak.md
docs/setup-tunnistamo.md
gdpr/README.md

docs: env-variables for the Tunnistamo and the Keycloak

---

kukkuu/settings.py

KK-1097 KK-1073.
Guide in Django-Helusers:
https://github.com/City-of-Helsinki/django-helusers?tab=readme-ov-file#oidc-back-channel-logout-endpoint.

feat: add back channel logout support

---

events/notifications.py
events/tests/snapshots/snap_test_notifications.py
events/tests/test_notifications.py
events/utils.py
subscriptions/notifications.py
subscriptions/tests/conftest.py
subscriptions/tests/snapshots/snap_test_notifications.py

feat: add is_obsoleted variable to the relevant email templates

---

events/consts.py
events/tests/snapshots/snap_test_notifications.py
events/tests/test_notifications.py
events/utils.py
users/models.py
users/tests/test_models.py

KK-1128.
The event and event group invitations needs to be accepted.

feat: do not send event invitations to those who have rejected them

---

kukkuu_mailer/apps.py

fix: add apps.py for Kukkuu mailer app

---

users/admin.py

feat: send auth service changing notifications from admin

---

users/admin.py

KK-1186 KK-1187.
List display should have a link from user to guardian and vice versa.
Also an admin should be able to filter users who don't have guardian link.

feat: add links and filters from guardian to user and vice versa in admin site

---

users/management/commands/send_user_auth_service_is_changing_notifications.py
users/services.py
users/tests/test_commands.py

refs KK-1184
[KK-1184](https://helsinkisolutionoffice.atlassian.net/browse/KK-1184)
[KK-1184]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1184 | feat: batch user is_obsolete updating in auth change command

---

users/tests/test_commands.py

refs KK-1184
[KK-1184](https://helsinkisolutionoffice.atlassian.net/browse/KK-1184)
[KK-1184]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1184 | feat: test auth change notifications command's query count

---

children/schema.py
docker-compose.yml
messaging/admin.py
messaging/schema.py
messaging/tests/snapshots/snap_test_api.py
messaging/tests/test_api.py
users/tests/test_services.py

KK-1108.
Improvements to https://github.com/City-of-Helsinki/kukkuu/pull/390.
What's done:
1. Bring back the support for protocol and occurrences filters in Message Query.
2. Improve some datetime imports.
3. Use Postgre version specific data location (Docker colume).
4. Add more fields and filters to messaging admin view.

Improvements to KK-1108

---

azure-pipelines-review.yml
azure-pipelines-test.yml
kukkuu/settings.py
projects/apps.py

test: enable browser init data creation in review and test envs

---

kukkuu/settings.py

ci: set default logging level with env var

---

kukkuu/oidc.py

fix: oidc debug extra usage

---

kukkuu/oidc.py

refactor: improve oidc debugging

---

common/tests/conftest.py
events/schema.py
events/tests/mutations.py
events/tests/snapshots/snap_test_api.py
events/tests/test_api.py
languages/tests/snapshots/snap_test_add_languages_command.py
projects/tests/snapshots/snap_test_api.py
projects/tests/test_api.py
pyproject.toml
users/tests/snapshots/snap_test_api.py
users/tests/snapshots/snap_test_services.py

fix: making event groups events publishable should not clear event group

---

projects/apps.py

KK-1235.
The browser test resources should not be created when running Pytests.

fix: browser test resources creation for pytests

---

events/admin.py
events/models.py

feat: enrolment reference id is viewable from the enrolment admin

---

events/admin.py

feat: add ticket validity to enrolment admin

---

events/admin.py

feat: autocomplete feature to ticket system admin event field

---

data/default_languages.csv
languages/tests/snapshots/snap_test_add_languages_command.py
reports/consts.py

refs KK-1250
[KK-1250](https://helsinkisolutionoffice.atlassian.net/browse/KK-1250)
[KK-1250]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1250 | Add Ukrainian language

---

kukkuu/settings.py
requirements-dev.txt
requirements-prod.txt
requirements.in
requirements.txt

KK-1348 KK-1365.
Used `pip-compile --upgrade` for requirements*.in files.
Removed the Google storage is not in use in any of the Kukkuu APIs environments.

Upgrade dependencies

---

README.md
docker-compose.yml

**Upgrade PostgreSQL** to 13 which the production in kukkuu is already using
- [KK-1349](https://helsinkisolutionoffice.atlassian.net/browse/KK-1349)
- [DevOps pipeline changes](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/10234) to change PostgreSQL 12 → 13
[KK-1349]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1349 | Upgrade PostgreSQL 12 → 13 in README & docker-compose.yml

---

dependabot.yml
requirements-dev.txt
requirements.txt

KK-1350.
Upgrade all the packages using `pip-compile --upgrade` for
`requirements.in` and `requirements-dev.in`.
Added a configuration file for dependabot. Use dependabot only for security updates.

Upgrade deps and configure Dependabot

---

browser-tests/package.json
browser-tests/yarn.lock

chore(deps): upgrade browser test packages

---

kukkuu/auditlog_settings.py

fix(auditlog): exclude mailer models from auditlog

---

.env.keycloak.example
azure-pipelines-review.yml
azure-pipelines-test.yml

Fix the Kukkuu Admin UI URL
Instead of
- https://kukkuu-admin-ui.test.hel.ninja/
- https://kukkuu-admin-ui.stage.hel.ninja/
the URLs for the Admin UI are:
- https://kukkuu-admin.test.hel.ninja/
- https://kukkuu-admin.stage.hel.ninja/

fix(config): admin ui url

---

reports/serializers.py

fix: report event serializer type hint warning

---

README.md

docs: releases, deployments and release-please

---

events/schema.py
events/tests/snapshots/snap_test_notifications.py
importers/tests/test_notification_importer.py
projects/consts.py
projects/tests/snapshots/snap_test_api.py
reports/serializers.py
subscriptions/schema.py
users/tests/snapshots/snap_test_api.py

Add project for year 2025 to load_project_data.py's constant data
using current production data.
Also some formattings were updated automatically with ruff.
- [KK-1394](https://helsinkisolutionoffice.atlassian.net/browse/KK-1394)
- PR #458
[KK-1394]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1394 | Add year 2025 project

---

README.md

Move & expand requirements in README.md
[KK-1379](https://helsinkisolutionoffice.atlassian.net/browse/KK-1379)
[KK-1379]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1379 | docs: move & expand requirements

---

sonar-project.properties

KK-1397.
Ignore snapshots and migrations.

chore: configure Sonarcloud

---

.env.keycloak.example
docker-compose.env.example

chore: add missing ALLOWED_HOSTS to env-files

---

events/consts.py
events/enums.py
events/models.py
events/schema.py
events/tests/test_api.py
events/tests/test_consts.py
events/tests/test_models.py

Add validation to AssignTicketSystemPasswordMutation, and refactor the related validation logics for maintainability.
See the commits for details.
[KK-1412](https://helsinkisolutionoffice.atlassian.net/browse/KK-1412)
[KK-1412]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1412 | Add validation to AssignTicketSystemPasswordMutation

---

.env.keycloak.example
browser-tests/tests/pages/login.ts
docker-compose.env.example
docs/setup-keycloak.md
kukkuu/auditlog_settings.py
kukkuu/settings.py
kukkuu/urls.py
requirements.in
requirements.txt

Based on django-helusers ["Adding Tunnistamo authentication"](https://github.com/City-of-Helsinki/django-helusers/tree/v0.13.0?tab=readme-ov-file#adding-tunnistamo-authentication) documentation & substituting Keycloak for Tunnistamo while reading it.
See also the [service integration document for Culture Kids](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8679030785/Palveluintegraatio+HP+-+Kukkuu+Kulttuurin+kummilapset).
- [KK-1409](https://helsinkisolutionoffice.atlassian.net/browse/KK-1409)
- Already done:
- [Azure DevOps pipeline PR](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/10812) for configuring the pipelines + `SOCIAL_AUTH_TUNNISTAMO_SECRET` values set to [dev](https://portal.azure.com/#@helsinginkaupunki.onmicrosoft.com/asse …

KK-1409 | Enable Helsinki city employees' django-admin Keycloak login

---

.pre-commit-config.yaml
requirements-dev.txt
requirements-not-from-pypi.txt
requirements.in
requirements.txt
subscriptions/tests/utils.py

Update all dependencies, including python-jose v3.3 → v3.4.
See commit for details.
Noticed that `pyasn1` got downgraded from 0.6.1 to 0.4.8.
This happened because python-jose v3.4.0 is [restricting pyasn1 version range to <0.5.0](https://github.com/mpdavis/python-jose/blob/3.4.0/setup.cfg#L38) (This changed from v3.3.0 to v3.4.0. Before there was no version restriction to `pyasn1`, now there is).
Should fix the following dependabot issues:
- https://github.com/City-of-Helsinki/kukkuu/security/dependabot/119 (Critical)
- https://github.com/City-of-Helsinki/kukkuu/security/dependabot/118 (Moderate)
[KK-1421](https://helsinkisolutionoffice.atlassian.net/browse/KK-1421)
[KK-1421]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

KK-1421 | Upgrade all dependencies, including python-jose v3.3 → v3.4

---

requirements.txt

Update dependencies to latest.
Fix dependabot security alerts:
- https://github.com/City-of-Helsinki/kukkuu/security/dependabot/120
- https://github.com/City-of-Helsinki/kukkuu/security/dependabot/121
- https://github.com/City-of-Helsinki/kukkuu/security/dependabot/120
- https://github.com/City-of-Helsinki/kukkuu/security/dependabot/121

fix(security): update dependencies to latest

---

.github/workflows/release-please.yml
pipelines/kukkuu-api-dev.yml
pipelines/kukkuu-api-review.yml

[ KK-1427](https://helsinkisolutionoffice.atlassian.net/browse/KK-1427)

build: default branch name change KK-1427

---

.github/workflows/ci.yml
sonar-project.properties

Refs: [KK-1429](https://helsinkisolutionoffice.atlassian.net/browse/KK-1429)
[KK-1429]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: add ci workflow

---

release-please-config.json

Use the same changelog sections as in other projects.

Add changelog sections to release-please configuration

---

kukkuu/settings.py

Update Azure storage settings.
Refs: KK-1462

KK-1462: Update Azure storage settings

---

kukkuu/settings.py
requirements.in
requirements.txt

Target newer library version and fix library update related configuration issue.

feat: update django-resilient-logger to v0.3.1

---

kukkuu/settings.py

feat: use DATABASE_PASSWORD if present in env
