children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, kukkuu/exceptions.py, kukkuu/urls.py, kukkuu/views.py
Added logic that sends all exceptions to Sentry, with the exception (hehehe) of:
* Bad Request type exceptions
* custom `KukkuuGraphQLError`s, which are meant for returning errors from the API which we don't want to Sentry
The PR contains also one unrelated bug fix.
=> KK-154 | Send GraphQL errors to sentry

children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py
* SubmitChildrenAndGuardian needs to be used first, and only then
* AddChild cannot be used before SubmitChildrenAndGuardian
* UpdateChild and DeleteChild cannot then be used before
SubmitChildrenAndGuardian either in practice (because one cannot
have children to update/delete)
=> KK-147 | Block mutations according to the usage flow

setup.cfg
Black somehow failed to format multiline strings in snapshots data so flake8 complains about line too long.
Since the data is generated from pytest so it would be ok to exclude the folders
=> Update flake8 excluded folders

kukkuu/settings.py, kukkuu/urls.py, requirements.in, requirements.txt
This reverts commit 1e8072be65351d127e26c4988da2971122c4c85f.
Adding secure-django broke something, at least GraphiQL.
=> Revert "Add max depth for API queries"

kukkuu/settings.py
We want to use a token's exp value instead of rejecting all tokens
older than 10mins.
=> Make OIDC_LEEWAY longer

common/models.py, common/tests/conftest.py, common/utils.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py, kukkuu/settings.py, venues/schema.py, venues/tests/snapshots/snap_test_api.py, venues/tests/test_api.py
Since `Event` and `Venue` have 1-n relationships with `Occurrence`. We have somehow to be able to create/update/delete occurrences from event and venue as well.
As I don't think we'll have the use case where occurrence created while updating `Venue`, I only made the nested CRUD in `Event`. For simplicity, for now only add and delete occurrence are supported in event update mutation.
Regarding translations, for some reason `django-parler` couldn't be able to recognise unsupported language code when creating new `translation`. A garbage row will be created in DB when someone trying to create a weird language code translation, and the app will break when we query that damaged object next time. I added a setting variable to avoid it. So the the model will ignore them when creating …
=> KK-181  KK-182 | Update  & delete events/venues/occurrences

children/schema.py
Previously queries returned relationship type as RelationshipType while
mutations used RelationshipTypeEnum.
=> KK-273 | Fix API queries to use RelationshipTypeEnum like mutations do

children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py, venues/schema.py, venues/tests/snapshots/snap_test_api.py, venues/tests/test_api.py
When querying occurrences from Event Node or Venue Node:
Turns out `DjangoConnectionField` will discard the annotation declared in OccurrenceNode default queryset so we need to resolve it manually in its parent Node.
=> Fix occurrences remaining capacity

.gitlab-ci.yml, kukkuu/settings.py, requirements.in, requirements.txt
Implement CDN to handle image upload from kukkuu QA env.
For prod we use Azure Storage instead of S3 and the configuration is not ready yet so I'll make a separated PR later. This PR is mainly focus on making upload image work on QA env.
Two gitlab config `STORAGE_BUCKET_STAGING_NAME` and  `STORAGE_BUCKET_STAGING_CREDENTIALS ` env var are already configured and the buckets is already created for the project.
=> KK-357 | Add cloud storage configuration

children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, common/tests/conftest.py, events/models.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py, events/tests/test_notifications.py, venues/tests/snapshots/snap_test_api.py, venues/tests/test_api.py
- Only staff user can query unpublished events (published_at=null) and occurrences of published event
- Added queryset to filter events based on user
- Added tests 
- Minor fix to `pastEvents` to return events which has no upcoming occurrences
=> Fix child events query to return only published events

kukkuu/settings.py
By default, in staging image uploaded will inherit permission of the bucket which has expired time.
We would like to have public, non-expiring url for those images.
Setting `GS_DEFAULT_ACL` to `publicRead` should solve this
=> Add default publicRead ACL to staging storage

kukkuu/settings.py
Disable Google storage file overwrite so duplicated name will be renamed to something unique so we don't accidentally delete other event images.
Azure Storage default setting for this is already False so we don't have to change it
=> KK-370 | Disable image overwrite on GCS

common/models.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py
so far I couldn't find any extra validation needed in events/occurrences/venue. So I only added validation for translation objects that requires default translation (defined by settings.LANGUAGE_CODE).
Note that backend only care about if the translation object is created, it doesn't care if all of the translation fields of that specific language are filled
=> KK-367 | Add translation validation

events/schema.py, venues/schema.py
By default GlobalID() field already has `required=True` It has to be set to `required=False` or use `ID` scalar to make it non-required in the input
=> KK-395 | Fix required fields in occurrence mutation

common/schema.py, events/schema.py, projects/schema.py, users/schema.py, users/tests/snapshots/snap_test_api.py, users/tests/test_api.py
Added `projects` field to `MyAdminProfileNode` because Kukkuu admin UI needs info about current user's projects. After that the old field `is_project_admin` is a bit unnecessary, so removed that.
Also removed `users` from `ProjectNode` because it leaks information about users, and isn't needed for anything anyway.
=> KK-453 | Project API improvements

users/__init__.py, users/apps.py, users/notifications.py, users/schema.py, users/tests/snapshots/snap_test_notifications.py, users/tests/test_notifications.py, users/utils.py
Added a new email notification which is sent after a guardian changes
her email address. The notification is sent to the new email address,
and only when the user has changed it herself, ie. the change comes
through UpdateMyProfileMutation.
=> KK-478 | Send email notification after guardian changed her email

events/models.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py
Because OccurrenceNode remainingCapacity and enrolmentCount fields
relied on annotated enrolmentCount to be available, they failed when
it wasn't available, like when doing UpdateOccurrenceMutation. Now
those fields will fallback to calculating the value for enrolmentCount
when it is not annotated.
=> KK-425 & KK-488 | Fix bug in OccurrenceNode remainingCapacity and enrolmentCount fields

children/models.py, children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, common/tests/conftest.py, common/utils.py, events/models.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py, events/tests/test_notifications.py, projects/models.py, users/models.py, users/tests/snapshots/snap_test_api.py, users/tests/test_api.py, venues/models.py, venues/schema.py, venues/tests/snapshots/snap_test_api.py, venues/tests/test_api.py
Changed viewing and admin CRUD mutations of Guardians (view only) Children (view only), Venues, Events and Occurrences to be allowed only for the corresponding project admins instead of all staff members like before.
Still to do later: Could use some new tests that check that a project admin of a different project cannot use the mutations. This is however not critical, because exploiting a possible hole would require a wrongdoer in the project admin group.
=> KK-458 | Remove staff based permissions

children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py
To support jumping straight into a specific page of results in children query, added limit and offset based pagination alongside the existing cursor based pagination.
=> KK-473 | Children limit / offset pagination

children/schema.py, children/tests/test_api.py, events/models.py
Previously unpublished events were returned in child queries'
past_events and available_events fields if the current user was a
project admin.
=> KK-465 | Always hide unpublished events in child node event fields

children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, events/filters.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py, kukkuu/settings.py
Implemented needed changes so that the UI can
* show enrolled events until half an hour after the occurrence has started
* show participated events as past events when the participated occurrence has passed
Implementation details in the commit messages.
=> KK-566 | Changes to event showing logic

common/utils.py, kukkuu/settings.py
Previously trying to get the API version was throwing an exception
when the revision could not be figured out, for example when running a
management script from outside the app's directory.
=> Fix API version string

subscriptions/models.py
FreeSpotNotificationSubscription.clean() was erroneously checking the remaining capacity of the occurrence on every clean, not just when creating a new subscription like it should have done.
=> Fix FreeSpotNotificationSubscription clean()

messaging/schema.py
The bug prevented using value null for event_id when adding a new
message. Also fine-tuned UpdateMessage mutation event_id handling a bit.
=> Fix a bug in AddMessage mutation

messaging/admin.py, messaging/models.py, messaging/schema.py, messaging/tests/snapshots/snap_test_api.py
Recipient count for an unsent message will be populated with the amount
of recipients there would be if the message was sent at that current
time.
=> KK-637 | Add recipient count to unsent messages

events/tests/test_api.py, kukkuu/settings.py
django-parler uses caching by default. That causes problems when there
are multiple Django processes and no proper cache backend in use
(which is exactly the situation in our QA and production envs ATM).
=> Disable django-parler caching

requirements-dev.txt, requirements-prod.txt, requirements.txt
Requirements compiled with pip-tools 5.5 have a sligthly different format than before. This commit does not cause any functional changes.
=> Compile requirements using pip-tools 5.5

README.md, kukkuu/settings.py, kukkuu/urls.py, reports/api.py, reports/apps.py, reports/drf_permissions.py, reports/models.py, reports/tests/snapshots/snap_test_api.py, reports/tests/test_api.py, requirements.in, requirements.txt, users/admin.py, users/factories.py
Added a separate REST API at URL `/reports/` which provides anonymized data to be used for reporting purposes. There is currently one endpoint, `/children/`, which returns all of the children with the exception of "orphan" ones, as we don't consider those valid cases ATM.
To access the API, one must use HTTP basic auth (or be logged in when `DEBUG` is `True`), and the user must also have Django permission `reports.access_report_api`.
[API documentation](https://kukkuu-kk-743-report-api-244.test.kuva.hel.ninja/reports/schema/redoc/)
=> KK-743 | Report API

kukkuu/tests/test_authentication.py, kukkuu/views.py
Reverts City-of-Helsinki/kukkuu#254
Heard from @tuomas777 that these AuthenticationErrors are in monitoring in purpose, because some real guardians have repeatedly encountered this issue.
=> Revert "Ignore authentication error like expired JWT from Sentry"

events/notification_service.py
KK-831. Tested in the QA pod where the email sending works properly: The PNG-attachment works in all tested devices.
=> Fixed the QR-code as file attachment

.github/workflows/production.yml, .github/workflows/staging.yml
The SMS messages sending fails in the notification-service. Maybe the sender name is too long.
=> Removed Translated SMS sender configuration from pipeline

children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, events/filters.py, events/models.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py
This PR adds an API to query all upcoming events and event groups for a child (`ChildNode.upcomingEventsAndEventGroups`). As opposed to the `availableEventsAndEventGroups` the new query also includes upcoming events to which the child might not be eligible to enroll.
`EventGroupNode` and `EventNode` include a new field `canChildEnroll(childId: ID)` which indicates if enrolling to the event is possible for the given child.
=> KK-839 | Add query for child's upcoming events and event groups

events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/snapshots/snap_test_notifications.py, events/tests/test_api.py, events/tests/test_notifications.py
Event group can be republished if there are new unpublished events in the event group which are marked ready for event group publishing.
=> KK-885 | Republish an event group

.pre-commit-config.yaml, children/models.py, children/schema.py, children/tests/test_api.py, events/models.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py, events/tests/test_models.py, messaging/tests/test_sending.py, requirements-dev.txt
This PR adds some functionality related to counting TicketSystemPasswords as enrolments.
- Move enrollment count calculation to the Child model
- `TicketSystemPassword` instance is counted as an enrollment (when requesting the amount of enrollments for a child)
- `Event/EventGroup.can_child_enroll` and `validate_enrolment` will respond as expected when the enrolment has been done using a TicketSystemPassword instance.
Extra:
- Bump black
=> KK-893 KK-890 | Count ticket system passwords towards yearly enrolment limit

children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, events/schema.py
Implemented query for fetching upcoming internal ticket system
enrolments (`Enrolment` model instances) and external ticket system
"enrolments" (assigned `TicketSystemPassword` instances). The enrolments
are sorted from earliest to latest where time is either the related
occurrence's time or the related event's latest occurrence's time
depending on which kind of enrolment it is.
The current purpose of this query is to provide a way for the UI to
fetch a child's all upcoming enrolments to "Tulevat tapahtumasi" (your
upcoming events) section in child profile view.
Example request:
```graphql
query ChildEnrolments {
child(id: "Q2hpbGROb2RlOjJhYzY1MjE3LWNhZDktNDhlNi05ZWVhLTNjMWIwODhhOTIyZA==") {
activeInternalAndTicketSystemEnrolments {
edges {
node {
__typename
... on …
```
=> KK-950 | Implement GraphQL query for fetching a child's all internal and external enrolments

events/models.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py
Example query:
```graphql
event(id: "RXZlbnROb2RlOjI=") {
name
ticketSystem {
... on TicketmasterEventTicketSystem {
freePasswordCount
usedPasswordCount
}
}
}
```
Example response:
```json
{
"data": {
"event": {
"name": "Parikoodauksen alkeet",
"ticketSystem": {
"freePasswordCount": 3,
"usedPasswordCount": 2
}
}
}
}
```
=> KK-914 | Add ticket system password counts to event API

events/schema.py, events/tests/test_api.py
During the typical ticket system password redeem flow in the UI, we need to first figure out whether the child has a password to the event or not, so it makes more sense to return null instead of an error in that situation.
=> KK-948 | Tweak ticket system password query

events/models.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/test_api.py
**WAITING FOR FRONTEND CHANGES BEFORE MERGING!**
Previously TicketSystemPassword query acted as mutation on the first
query run. Remove the mutation functionality from the query altogether.
Add test cases:
- test_event_ticket_system_password_own_child_password_exists
- test_event_ticket_system_password_own_child_no_password
Remove as unnecessary:
- Event.get_or_assign_ticket_system_password function
- test_event_ticket_system_password_assignation test
- test_event_ticket_system_password_assignation_no_free_passwords test
[KK-948](https://helsinkisolutionoffice.atlassian.net/browse/KK-948)
Before merging frontend should be updated first to use the AssignTicketSystemPasswordMutation from PR #289.
=> KK-948 | Remove side-effects from TicketSystemPassword query

events/models.py, events/tests/test_notifications.py, events/utils.py, messaging/service.py
KK-984.
The object instance save-process should be handled in a transaction,
so if any errors occurs, the whole process is rolled back.
The sending of notifications (emails and sms) cannot be in that same transaction,
because a sent message cannot be rolled back --
the receiver has already received the message.
The notifications context should be processed as much as possible
before the actual sending, so that any issues should have been already raised,
before any of the messages has been delivered yet.
=> Process notifications sending outside the atomic transaction of saving of events

.github/workflows/ci.yml, README.md, children/factories.py, children/models.py, children/tests/test_models.py, reports/api.py, reports/tests/snapshots/snap_test_api.py, reports/tests/test_api.py
https://about.codecov.io/blog/message-regarding-the-pypi-package/
> On April 12, 2023, Codecov removed the codecov package from PyPI.
> Our intent was to remove a deprecated, rarely-used package from active
> support.
refs TC-67 (codecov removed from PyPi)
refs KK-997
add hashes to reporting API:
- child_birthdate_postal_code_guardian_emails_hash
- Salted hash of child's birthdate, postal code and guardians'
emails.
- child_name_birthdate_postal_code_guardian_emails_hash
- Salted hash of child's name (i.e. first name and last name),
birthdate, postal code and guardians' emails.
- add to tests:
- test_child_birthdate_postal_code_guardian_emails_hash
- test_child_name_birthdate_postal_code_guardian_emails_hash
- test_child_hashes_email_change
- more coverage to test_children_endpoint
refs …
=> KK-997 | feat: add hashes to reporting API to evaluate number of unique accounts

children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, reports/tests/snapshots/snap_test_api.py
KK-428
The updating of the child's birthdate field should not be possible anymore. This pull request requires changes from the client too, because it is currently including the birthdate-field in the mutation input.
NOTE: There is an [alternative PR](https://github.com/City-of-Helsinki/kukkuu/pull/333) for this that does not remove but deprecates the field from the child update mutation input.
NOTE: https://github.com/City-of-Helsinki/kukkuu/pull/336 and https://github.com/City-of-Helsinki/kukkuu/pull/336 will force some API changes anyway, so therefore this PR is recommended over the https://github.com/City-of-Helsinki/kukkuu/pull/333.
=> Child update mutation input should not have birthdate field

users/admin.py
KK-1090.
When the results were filtered, there appeared some empty options,
which then prevented the saving of the group.
=> fix: admin site user-group-relationship shouldn't be filtered for admins only

users/notifications.py
KK-1071. The CI fails to build the application:
```
django.db.utils.ProgrammingError: relation "django_content_type"
does not exist
```
=> fix: build issues in CI environment

README.md
github & gitlab should both support mermaid syntax already, and e.g. JetBrains PyCharm supports mermaid syntax using a plugin.
refs KK-1073
=> docs: add Django model hierarchy used in GDPR API data export to README

events/admin.py, projects/models.py
Fix the projects objects manager -- It broke when the serializable mixin was taken in use.
Also make the child field of the TicketSystemPassword admin to autocompletable / searchable.
=> fix: projects model objects manager

requirements.in, requirements.txt
KK-1097 KK-1117.
When the GDPR API requests data from the Kukkuu API,
it must use an authorization token (which in this point is issued by Tunnistamo).
The issued JWT auth token has the amr-field in a string format, 
when it should be a list. Upgrading the helusers-package fixes the auth issues.
=> fix: upgrade the django-helusers to fix issues with GDPR API auth

common/decorators.py, events/models.py, events/tests/test_notifications.py, events/utils.py
KK-1035.
Added a new common decorator that can be used to execute tasks in background
in a new thread.
If there are thousands of email recipients, the process of creating the mails
will take tens of seconds. While the process is handled in the same
request handler as the event state change, the response takes long to be sent,
which leads to a connection timeout, that will write an error message
to the admin UI. To prevent that, the state change could be done as an atomic
operation as it has always been done, but the emails could be sent in an another
thread. The response is then sent when the atomic process finishes and the email
sending is not awaited.
More about the threading for email sending:
- https://ozcanyarimdunya.github.io/dj_threading/
- …
=> feat: send event and event group publish notification in a thread

children/tests/mutations.py, children/tests/queries.py, children/tests/test_api.py, children/tests/test_notifications.py, events/tests/mutations.py, events/tests/queries.py, events/tests/test_api.py, events/tests/test_notifications.py, gdpr/tests/snapshots/snap_test_gdpr_api.py
what was done (and nothing else):
- moved GraphQL queries, that were in variables, to queries.py in order of their appearance in the original source file
- moved GraphQL mutations, that were in variables, to mutations.py in order of their appearance in the original source file
- imported the moved queries from queries.py
- imported the moved mutations from mutations.py
NOTE:
- variables to queries/mutations were NOT moved but left where they were in the original source file
refs KK-1143 (refactoring came up in code review discussion)
[KK-1143](https://helsinkisolutionoffice.atlassian.net/browse/KK-1143)
[KK-1143]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: move named GraphQL query/mutation variables to own files

.env.keycloak.example, kukkuu/settings.py
KK-1159.
Added an env-variable to set the `GDPR_API_AUTHORIZATION_FIELD`. The actual env specifiv value is set in the [pipeline configuration](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/8683).
=> fix: add env-variable for GDPR API authorization field

children/schema.py, children/tests/snapshots/snap_test_api.py, children/tests/test_api.py
change SubmitChildrenAndGuardianMutation's email validation behavior:
- no input email -> use user's email
- empty input email -> use user's email
- non-empty input email different from user's email -> error
- non-empty input email same as user's email -> ok
refs KK-1175
[KK-1175](https://helsinkisolutionoffice.atlassian.net/browse/KK-1175)
[KK-1175]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
kukkuu-ui changes:
- https://github.com/City-of-Helsinki/kukkuu-ui/pull/567
=> KK-1175 | feat: always use user's email in SubmitChildrenAndGuardianMutation

.prod/uwsgi.ini
KK-1157.
Increasing the buffer-size will allow bigger requests which will allow e.g. to include big lists of AD-group memberships in a authentication token.
Refs
https://github.com/City-of-Helsinki/linkedevents/commit/1bd9ca89acc3f7f2becb70ce3b1b90faca67dc8c
=> chore: increase the buffer-size for uWSGI

users/admin.py, users/management/commands/send_user_auth_service_is_changing_notifications.py, users/models.py, users/notifications.py, users/schema.py, users/services.py, users/tests/snapshots/snap_test_models.py, users/tests/snapshots/snap_test_notifications.py, users/tests/snapshots/snap_test_services.py, users/tests/test_commands.py, users/tests/test_models.py, users/tests/test_notifications.py, users/tests/test_services.py, users/utils.py
KK-1138 KK-1140 KK-1141 KK-1142.
Refactored the old notification service code a bit by moving the functions from utils-file to new classes in services.py.
The notification template should offer the default dates for the service change, because otherwise it would always need a developer to generate a new notification content.
A management command that has the following inputs:
- date of the change of the auth service can be given as a formatted string, e.g. "17.6.2024". Use it with "-d 17.6.2024".
- a user joined date filter can be used to filter the queryset of the guardians. Use "-j 2024-06-06T15:00:00".
- by default the queryset includes only the obsoleted guardians, but all the guardians can be included with "--include_non_obsoleted".
- a list of emails can be used as a recipient …
=> Make it possible to send a mass email about the auth service is changing

kukkuu/settings.py, kukkuu_mailer/admin.py
KK-1172.
Rename the django_mailer result-column in a list_display view.
1. The column title for the result field has been changed.
2. The list filter title for the result field has been changed. 
NOTE: In order to override any admin site classes, a new django app must be added in the INSTALLED_APPS settings after the app that is being overridden.
=> fix: improve the django_mailer admin list display view

requirements.in, requirements.txt, users/admin.py, users/services.py, users/tests/snapshots/snap_test_notifications.py, users/tests/snapshots/snap_test_services.py
KK-1183.
Fix the multiline list items markdown rendering.
Installed markdown library to render actual markdown with the admin action.
Markdown spec for multiline list items and more:
https://daringfireball.net/projects/markdown/syntax#list.
✅ The list item is a multiline item with event short description on 2nd line.
✅ Each enrolment is a one list item
✅ The short description is indented (because in markdown it means that the list item has second line and it is rendered as P-tag.)
✅ The email should look good and human readable even without the markdown renderer.
✅ The markdown is parsed properly
=> fix: children event history markdown line endings and indentations

users/admin.py, users/management/commands/send_user_auth_service_is_changing_notifications.py, users/services.py, users/tests/test_commands.py
send_user_auth_service_is_changing_notifications management command:
- "-o" / "--obsolete_handled_users":
- will obsolete the handled users i.e. set their User model's
is_obsolete values to True, defaults to False
- "b <int>" / "--batch_size <int>":
- will use the batch size for bulk updating users and guardian
queryset iteration, defaults to 1000
refs KK-1184
[KK-1184](https://helsinkisolutionoffice.atlassian.net/browse/KK-1184)
[KK-1184]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KK-1184 | feat: add --obsolete_handled_users & --batch_size to auth change command

users/admin.py
KK-1186
Quite trivial fix, but the new guardian and user admin actions are missing the success messages.
=> fix: add missing success messages to user and guardian admin actions

kukkuu/settings.py, kukkuu_helusers_admin/admin.py, kukkuu_helusers_admin/apps.py, users/admin.py
KK-1199.
Add a new django app to override `django_helusers` admin views:
1. Add search fields to AD-group,  group and AD-group-mappings administration.
2. Add autocomplete fields to AD-group-mappings admin form.
3. Add autocomplete field to Group admin's UserInLine
Autocomplete in Group admin form:
Autocomplete fields in AD-group mappings admin form:
Search field in AD-group mappigns admin listing:
Search field in AD-group admin listing:
=> feat: add search and autocomplete fields to group and ad groups admin

browser-tests/tests/initialData.ts, browser-tests/tests/pages/event.ts, browser-tests/tests/pages/eventGroup.ts, browser-tests/tests/pages/message.ts, browser-tests/tests/pages/project.ts, browser-tests/tests/pages/venue.ts, browser-tests/tests/utils/getDropdownOption.ts, events/admin.py
KK-1200. Fix event group admin.
1. Add an id as a "link column", since the name can sometimes be empty.
2. Add a fallback option for name and short descriptions in the list
display.
3. Add a missing search field that search for name and short
description.
KK-1201. Fix event admin.
Search by event and event group name.
=> fix: improve event and event group admins with safegetters and searches

Dockerfile, kukkuu/settings.py, projects/apps.py
KK-1168.
Create Group, ADGroup, and Project resources for browser tests. This is done in the project app's ready-function and with a post_migrate -signal.
In Django, the post_migrate signal is emitted in the following scenarios:
After Migrations: It is triggered immediately after Django successfully applies migrations to your database. This includes both initial migrations when setting up your project and subsequent migrations when you make changes to your models.
During Tests (with --keepdb): If you run your Django tests with the --keepdb flag, the post_migrate signal will also be triggered after the test database is initialized. However, if you use a separate test database for each test case, the signal might be emitted for each test.
Management Commands: Some Django management …
=> feat: provide initial browser test data automatically

events/admin.py, messaging/admin.py
KK-1212.
Improves the https://github.com/City-of-Helsinki/kukkuu/pull/390/files#diff-c327ae44d42381dc0896cb42446dbdfd7a515a48ae6b0bfb4a971941c007c44b by fixing the subject and link field.
Fixing this situation when the current locale does not have a subject:
with this
=> fix: link and subject field in the messaging admin list display

children/schema.py, common/schema.py, messaging/schema.py, messaging/tests/snapshots/snap_test_api.py, messaging/tests/test_api.py, projects/tests/test_api.py
KK-1214.
The React-Admin of the Kukkuu Admin UI has some special needs for the pagination: the API must offer limit-offset-pagination with a count field. Also, it would be good if the messages could be sorted by the creation date (and sent date).
=> Add pagination and sorting to messages query

common/utils.py, events/admin.py, events/models.py, kukkuu/urls.py, reports/api.py, reports/consts.py, reports/serializers.py, reports/tests/conftest.py, reports/tests/snapshots/snap_test_api.py, reports/tests/test_api.py
KK-1026.
Added 3 new API view sets (under path `/reports` ):
1. The most important one: the Events report API. An optimised list view that is mostly used by PowerBI reports.
2. Event Group list and detail view, to offer more details for events report API.
3. Venue list and detail view, to offer more details for events report API.
Multiple new serializers were needed. Serializers for
1. Event
2. Occurrence
3. EventGroup
4. Project
5. Venue
Optimize the serializers so that they don't fetch trivial data for Power BI reports.
The list view does not need all the translations or calculations, since they can be offered
from the details/retrieve view. For example, it does not make sense for PowerBI to read the name
multiple times from every event group that is linked to event. So the name of the …
=> Event report API with event group and venue view sets as helpers

.gitlint, .pre-commit-config.yaml, README.md
relaxed gitlint rules:
- allowing 72 character long titles instead of 50 to be more lenient
- allowing >72 character http and https URLs in git commit messages,
e.g. https://www.example.org/this-is-a-very-long-url-that-can-not-be-split-without-breaking-it-somehow
also:
- update default python version in pre commit config from 3.9 to 3.11
- add general.regex-style-search=true to gitlint configuration so
gitlint doesn't show a warning about it (See below)
gitlint's warning about regex match/search semantics:
```
gitlint will be switching from using Python regex 'match' (match
beginning) to 'search' (match anywhere) semantics. Please review your
ignore-by-title.regex option accordingly. To remove this warning, set
general.regex-style-search=True. More details: …
```
=> chore: configure gitlint to be more lenient & add notes to README.md

browser-tests/package.json
KK-1247.
Pipeline changes: https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/9899
Add an option to run Testcafe browser tests with Chromium instead of
Chrome. There have been some issues with the Chrome that prevents using
it in CI environment:
- https://github.com/DevExpress/testcafe/issues/8286
- https://github.com/DevExpress/testcafe/issues/8300
- https://github.com/DevExpress/testcafe/issues/8304
- https://github.com/DevExpress/testcafe/issues/8307
=> test: add an option to run Testcafe test with chromium

events/schema.py, events/tests/queries.py, events/tests/test_api.py
NOTE:
- This field is available to all logged-in users, no anonymous
access, but no project permission required either.
also:
- add @staticmethod to all resolve functions (See below the Graphene
documentation) in ExternalEventTicketSystem so SonarCloud doesn't
complain about the first parameter not being `self` (i.e. "self"
should be the first argument to instance methods python:S5720)
From Graphene documentation:
https://docs.graphene-python.org/en/latest/types/objecttypes/#resolverimplicitstaticmethod
> One surprising feature of Graphene is that all resolver methods are
> treated implicitly as staticmethods. This means that, unlike other
> methods in Python, the first argument of a resolver is never self
> while it is being executed by Graphene.
> If you prefer your code to be more …
=> KK-1322 | Add hasAnyFreePasswords to ExternalEventTicketSystem

.pre-commit-config.yaml, kukkuu/tests/test_pre_commit_ruff_version.py
also:
- update ruff to same version in .pre-commit-config.yaml as it is in
requirements-dev.txt, they were out of sync
=> Test ruff is same in requirements-dev.txt and .pre-commit-config.yaml

children/schema.py, events/models.py, kukkuu/settings.py, kukkuu/views.py, venues/schema.py
Fix warnings:
- sentry_sdk deprecation warning by using current scope
- graphene-django warning that DjangoObjectType needs fields/exclude by explicitly defining the fields
- DEFAULT_FILE_STORAGE deprecation warning by using STORAGES instead
- Needs [DevOps PR #10214](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/10214) for this change to work in pipelines
- "The USE_L10N setting is deprecated" deprecation warning by removing it, as the default is the same as the set value
- Remove ChildNode deprecation warnings and document fields' behavior
- [KK-1357](https://helsinkisolutionoffice.atlassian.net/browse/KK-1357)
- https://github.com/City-of-Helsinki/kukkuu/pull/437 as an approved extra
- [DevOps PR …
=> KK-1357 | Fix warnings

custom_health_checks/README.md, custom_health_checks/apps.py, custom_health_checks/backends.py, custom_health_checks/tests/test_backends.py, custom_health_checks/tests/test_healthz.py, custom_health_checks/views.py, kukkuu/settings.py, kukkuu/urls.py, requirements.in, requirements.txt
KK-1334.
Copy the `custom_health_checks` implementation from the Notification
Service. With that, check that the connection from app to the database
is healthy.
Reference:https://github.com/City-of-Helsinki/notification-service-api/tree/master/custom_health_checks.
The development team has decided that the readiness probe should
response with some refined server release and build information. Copied
the readiness probe implementation from Notification Service to make the
Kukkuu consistent with other apps.
Reference:
https://github.com/City-of-Helsinki/notification-service-api/blob/master/notification_service/urls.py.
=> Improve the readiness and liveness probes

docker-compose.yml
KK-1367.
Usage example: `DOCKER_TARGET=production podman compose up --build`.
=> chore(docker): consistent name for docker target

hel_django_auditlog_extra/mixins.py
KK-1113.
In some cases, the context does not have the changelist initialized, so it is better to fetch the change list instance with `ModelAdmin.get_changelist_instance`. Also, the post requests which are only used by the django admin actions are just logging the reads as duplicated.
=> fix(auditlog-extra): admin mixin should use get_changelist_instance

children/tests/snapshots/snap_test_api.py, children/tests/test_api.py, events/schema.py, events/tests/snapshots/snap_test_api.py, events/tests/snapshots/snap_test_notifications.py, events/tests/test_api.py, importers/tests/test_notification_importer.py, projects/consts.py, projects/management/commands/load_project_data.py, projects/migrations/0009_add_projects_data.py, projects/models.py, projects/tests/snapshots/snap_test_api.py, projects/tests/test_api.py, projects/tests/test_load_project_data.py, reports/serializers.py, subscriptions/schema.py, users/tests/snapshots/snap_test_api.py, users/tests/test_api.py
KK-1394.
Add a new data migration file that adds the missing mandatory projects, 1 per year after year 2020. When children are added to the system, they always needs to be linked to a year project of their birth year.
Update the tests, because the new data migration will add more projects to the database and some of the tests were trusting in 1 specific state.
Fix the Project model `__str__` with a safe translation getter, since the management command has not set any language by default.
=> fix: update projects to db using migrations and management commands

kukkuu/settings.py, kukkuu/tests/test_sentry.py
KK-1396.
Sentry should ignore errors related to expired authentications, since it
is not a system error, but a feature related to JWT usage.
NOTE: https://github.com/City-of-Helsinki/kukkuu/pull/461 was created first, but later rebased to this.
=> feat(sentry): ignore authentication expired errors in Sentry

kukkuu/settings.py
With `from helusers.defaults import SOCIAL_AUTH_PIPELINE  # noqa: F401`
the post logout redirect uri was /helauth/logout/complete/ which didn't
match the /admin/ value given in the service integration document and
configured to Keycloak.
Updating the service integration document and configuring Keycloak to
use the post logout redirect uri of /helauth/logout/complete/ would also
fix this problem, and would log out the user from the AD also AFAIK.
Removing `from helusers.defaults import SOCIAL_AUTH_PIPELINE` makes the
post logout redirect uri match /admin/ i.e. the value configured to
Keycloak, and fixes logout from django-admin. A side effect of this is
that the user is not logged out from the AD.
[KK-1409](https://helsinkisolutionoffice.atlassian.net/browse/KK-1409)
Previously trying to …
=> KK-1409 | Fix django-admin logout

children/tests/snapshots/snap_test_models.py, children/tests/test_api.py, common/templates/notification_change_list.html, events/factories.py, events/tests/snapshots/snap_test_api.py, gdpr/tests/snapshots/snap_test_gdpr_api.py, importers/templates/notification_change_list.html, messaging/tests/snapshots/snap_test_api.py, requirements.in, requirements.txt, subscriptions/tests/snapshots/snap_test_api.py, users/tests/snapshots/snap_test_models.py, users/tests/snapshots/snap_test_notifications.py, verification_tokens/admin.py, verification_tokens/factories.py
Fix SonarCloud reliability issues, see commits for details.
Specifically fix the 5 reliability issues that dropped the reliability rating to C:
Tested `//NOSONAR` in the HTML files with [SonarQube for IDE plugin for PyCharm](https://plugins.jetbrains.com/plugin/7973-sonarqube-for-ide). Without the `//NOSONAR` an error was shown using the plugin, with the `//NOSONAR` it was not shown.
- [KK-1416](https://helsinkisolutionoffice.atlassian.net/browse/KK-1416)
- [SonarCloud issues](https://sonarcloud.io/summary/overall?id=City-of-Helsinki_kukkuu-api&branch=master)
- ![image](https://github.com/user-attachments/assets/8f729ee2-2ab0-40b6-abdb-2a09ee2ea931)
[KK-1416]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> KK-1416 | Fix SonarCloud reliability issues

README.md
This update improves the README by adding instructions for setting up docker-compose.env. It guides users to copy the example file and configure SOCIAL_AUTH_SECRET with the appropriate secret from keyvault.
**Changes**:
- Updated README.md with setup instructions for docker-compose.env.
**Why**:
- Helps new developers quickly configure their environment.
- Ensures proper setup of authentication secrets.
=> docs: add mention to set secret from the keyvault

kukkuu/settings.py
Django-admin Keycloak login related fix:
Revert 2d14cbe34119a8fbce8216ea8f838724ae9a92b1 which caused bug
https://helsinkisolutionoffice.atlassian.net/browse/KK-1422 i.e.
"AD-login to django-admin & kukkuu-admin UI with same AD user creates
two different users in backend".
Needs updating of post logout redirect URIs at Keycloak from /admin/ to
/helauth/logout/complete/, updated the post logout redirect URIs to
Kukkuu's service integration document:
https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8679030785/Palveluintegraatio+HP+-+Kukkuu+Kulttuurin+kummilapset
Asked Solution Office (i.e. Ratkaisutoimisto) on 2025-03-04 to
update the post logout redirect URIs to Keycloak.
[KK-1422](https://helsinkisolutionoffice.atlassian.net/browse/KK-1422)
[KK-1422]: …
=> KK-1422 | Use `helusers.defaults.SOCIAL_AUTH_PIPELINE` to deduplicate users

.pre-commit-config.yaml, requirements-dev.txt, requirements.txt
logout got broken in 53dde1146834c96395c603fe03bd5973b4ead8f1
django-helusers fixed logout in City-of-Helsinki/django-helusers#114
which was released in django-helusers v0.13.3
refs KK-1422
- [KK-1422](https://helsinkisolutionoffice.atlassian.net/browse/KK-1422)
- https://github.com/City-of-Helsinki/django-helusers/releases/tag/django-helusers-v0.13.3
- https://github.com/City-of-Helsinki/django-helusers/pull/114
[KK-1422]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KK-1422 | Fix logout by upgrading deps to latest, incl. django-helusers v0.13.3

.prod/uwsgi.ini, docker-entrypoint.sh, requirements-prod.in, requirements-prod.txt
Improve uWSGI options:
- Restart a worker after 1000 requests (max-requests)
- Restart a worker every hour (max-worker-lifetime)
- Restart a worker after 300MB resident memory usage (reload-on-rss)
- Restart a worker by force after 60 seconds (worker-reload-mercy)
- Use strict mode to catch unknown uWSGI options (strict)
- Require an application module to start (need-app)
- Avoid multiple interpreters (single-interpreter)
- Only use processes for concurrency, so only run one thread per
process
- Suppress errors about clients closing sockets
- Add Harakiri options
- Add Sentry-setup
- Add uwsgitop and settings
Refs: KK-1453
=> KK-1453: uWSGI improvements

kukkuu/settings.py
Add `AZURE_QUERYSTRING_AUTH = False`. This setting prevents Django from appending SAS tokens to generated URLs.
When set to False, Django will generate URLs without authentication parameters.
Refs: KK-1462
=> KK-1462: Prevent SAS token from being exposed in client URLs

kukkuu/settings.py, requirements.in, requirements.txt
DRAFT:
KK-1442
Kukkuu is using formatted, but non-structured logging. Transition to JSON logging by making use of the `django-logger-extra` (https://github.com/City-of-Helsinki/django-logger-extra) library.
Also make request id as part of the logger context and pass it also to the django-auditlog as additional_data property.
The request id is read from the incoming header `X-Request-ID` or if it's not present, generated using UUID v4.
=> feat: transition to structured (json) logging

kukkuu/settings.py
SAS-tokens are not needed for now,
therefore remove possibility to use them.
Refs: KK-1462
=> KK-1462: Simplify Azure storage settings
